name: flutter_story_app
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+7

environment:

  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  carousel_slider: ^4.2.1
  #  carousel_pro: ^1.0.0
  flutter_screenutil: ^5.9.0
  #  path: ^1.8.1
  path_provider: ^2.1.2
  path_provider_foundation: ^2.3.2
  sqflite: ^2.3.2
  image_picker: ^1.0.7
  flutter_share: ^2.0.0
  #  share_plus: ^7.2.1
  social_share: ^2.3.1
  #  share: ^0.6.5+3
  numberpicker: ^2.1.2
  shared_preferences: ^2.2.2
  provider:
  flutter_quill: ^8.6.3
  #  url_launcher: ^6.1.5

  rate_my_app: ^2.0.0
  fluttertoast: ^8.2.4
  #  progress_dialog: ^1.2.4
  webview_flutter: ^4.7.0
  mime: ^1.0.5
  flutter_material_color_picker: ^1.2.0
  tuple: ^2.0.2
  package_info_plus: ^5.0.1
  flutter_mailer:
  flutter_colorpicker: ^1.0.3
  html_unescape: ^2.0.0
  flutter_widget_from_html_core: ^0.14.11
  #admob_flutter: ^3.0.0
  colorful_safe_area: ^1.0.0
  #  auto_direction: ^0.0.6
  #  google_mobile_ads:
  html: ^0.15.4
  flutter_picker: ^2.1.0
  url_launcher: ^6.2.6
  flutter_inappwebview: ^6.0.0
  widget_zoom: ^0.0.4
  shimmer: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/
    - packages/flutter_story_app/summernote/summernote.html
    - packages/flutter_story_app/summernote/summernote-lite.min.css
    - packages/flutter_story_app/summernote/summernote-lite.min.js
    - packages/flutter_story_app/summernote/summernote-lite.min.js.map
    - packages/flutter_story_app/summernote/jquery-3.4.1.slim.min.js
    - packages/flutter_story_app/summernote/font/summernote.eot
    - packages/flutter_story_app/summernote/font/summernote.ttf
    - packages/flutter_story_app/summernote/font/summernote.woff
    - packages/flutter_story_app/summernote/font/summernote.woff2

flutter_intl:
  enabled: true
#  class_name: S # Optional. Sets the name for the generated localization class. Default: S
#  main_locale: es
